### ISSUE TITLE
Missing / odd cumulative values

### ISSUE THREAD

**Issue by bpbond** [bpbond/dwp_peyton#1]
@apeyton :

> There are no values for cum CO2 and CH4 for core 39 (despite having data for the flux measurements > 0). There are also areas where the cum values flat-line (see slides 1 and 2).  Could you please check into script for calculating cum CH4 and CO2?

**Comment by bpbond** [comment]
Re core 39 - data seems to be there as far as I can see.

**Comment by apeyton** [comment]
? flux or cum data? that you see.

**Comment by bpbond** [comment]
I was looking at `cumCO2_flux_mgC`, which is what you plotted.

**Comment by apeyton** [comment]
there is no intact data for Core 39 in the files I sent???
![core 39](https://cloud.githubusercontent.com/assets/15001822/13438899/e091d394-df9f-11e5-99cf-a4f5e830fda2.png)

**Comment by bpbond** [comment]
Ah, OK, thanks. Sorry--haven't look at these data in months.

**Comment by apeyton** [comment]
ps. that is why I included a figures doc. :) to help refresh memory.

**Comment by bpbond** [comment]
![co2](https://cloud.githubusercontent.com/assets/1956468/13439516/ef7a5f04-dfbb-11e5-8beb-4820510f5a99.png)
![ch4](https://cloud.githubusercontent.com/assets/1956468/13439550/16040bc0-dfbc-11e5-81d3-b4ae00a68e01.png)

These two problems (missing cores, other flatlining) both symptoms of the same bug, which is now fixed.

**Comment by bpbond** [comment]
Fixed--closing.

**Comment by apeyton** [comment]
Thank you
