### ISSUE TITLE
Discrepancies in number of points

### ISSUE THREAD

**Issue by bpbond** [bpbond/dwp_peyton#2]
@apeyton :

> For some cores, there are many data points for the first part of the incubation (i.e. first 200 mins, ex: Core 1 has 18 rows/values for flux under 200 mins), whereas some cores (ex: core 14) ONLY have 6 values for fluxes under 200 mins. Thoughts? Is this an issue I should be worried about? Some cores (ex: core 52) have flux values that look like we chopped off the beginning (see slide 3). Is this related? I mean, can you check into how elapsed minutes was calculated? I remember having negative values for this the first time and you fixed that, but I am wondering if there are some other issues with it too.

**Comment by bpbond** [comment]
- Different number of points: seems like most cores have a similar number of observations in the first 200 minutes, but eight have many more. Looking at the timestamps, it seems like the higher-observation cores were being measured every 9 minutes or so, while the others have observations every 38 minutes. Right now I don't know why this is the case.
  ![n200](https://cloud.githubusercontent.com/assets/1956468/13440180/ca839596-dfbe-11e5-927a-6fbfc8482b80.png)
- Re core 52, I don't _see_ a problem, in that the flux rates for that core were very high for the first few hours, then dropped down. Slide 3 shows this correctly (note that it's graphing instantaneous fluxes, not cumulative fluxes).
- `elapsed_minutes` is calculated based on the STARTDATE and STARTTIME fields in the valve map (DWP2014_Respiration Sample Key_21July2015.xlsx). There are in fact negative values for `elapsed_minutes`, and again, those particular cores have many more, as expected:
  ![nneg](https://cloud.githubusercontent.com/assets/1956468/13440282/4ee845ca-dfbf-11e5-953c-77e895151a41.png)

**Comment by bpbond** [comment]
One thing that could cause the discrepancy (in number of samples below 200 minutes, above) is if we have a mapping problem, and are incorrectly attributing data to cores. I'm out of time at the moment, but this is where I'm going to pick up again: take e.g. Core 1 and track back those ~35 observations before 200 minutes. Is something going wrong, so that others cores' data are being attributed to Core 1?

@apeyton: I see missing cores numbers above, but it seems like they line up with values that are missing in your `DWP2014_Respiration Sample Key_21July2015.xlsx` file (no 2, 9, 11, 16...). Right?

**Comment by apeyton** [comment]
Aha! **It is not that most cores have fewer measurements, it is that 8 cores have many more measurements!** That makes sense to me. One day (i.e. I measure only 8 cores/day) the controller for the picarro was set up differently (based on someone else using it); it was set to run measurements much more frequently than I normally do. I didn't catch it until a few hours into the run. I will verify that these are the cores from that day. 

As to the neg values. I removed all negative elapsed time for my analyses.

**Comment by bpbond** [comment]
Cool! Closing this for now; we can reopen if necessary.
